# Docker Compose file for building and running.
version: "3.4"

services:
  bookmarks:
    container_name: bookmarks
    image: joyofplaying.com/planning/bookmarks:latest
    build:
      context: .
      dockerfile: ./DOCKERFILE
    environment:
      - TZ
    ports:
      - "8000:80"
